# Generated by Django 4.0.3 on 2022-03-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoDinamicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='desc',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
