# Generated by Django 4.0.3 on 2022-05-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoDinamicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
