# Generated by Django 4.0.3 on 2022-03-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MotoDinamicApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=128)),
            ],
        ),
    ]
