# Generated by Django 4.0.3 on 2022-03-28 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MotoDinamicApp', '0003_cliente_factura_moto_ordenesdeingreso_servicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente_Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MotoDinamicApp.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFactura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MotoDinamicApp.factura')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_problema', models.CharField(max_length=228)),
                ('fecha_ingreso', models.DateTimeField()),
                ('info_adicional', models.CharField(max_length=228)),
                ('idMoto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MotoDinamicApp.moto')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeIngreso_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOrdenDeIngreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MotoDinamicApp.ordendeingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('desc', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='OrdenesDeIngreso',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
        migrations.RemoveField(
            model_name='tipoproducto',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='tiposervicio',
            name='desc',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='calle', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='idTipoServicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='MotoDinamicApp.tiposervicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='idTipoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MotoDinamicApp.tipoproducto'),
        ),
        migrations.AddField(
            model_name='ordendeingreso_servicio',
            name='idServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MotoDinamicApp.servicio'),
        ),
        migrations.AddField(
            model_name='factura_servicio',
            name='idServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MotoDinamicApp.servicio'),
        ),
        migrations.AddField(
            model_name='factura_producto',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MotoDinamicApp.producto'),
        ),
        migrations.AddField(
            model_name='cliente_factura',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MotoDinamicApp.cliente'),
        ),
        migrations.AddField(
            model_name='cliente_factura',
            name='idFactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MotoDinamicApp.factura'),
        ),
    ]
